# Generated by Django 5.2.5 on 2025-08-27 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='Место')),
                ('time', models.DateTimeField(verbose_name='Время')),
                ('action', models.TextField(verbose_name='Действие')),
                ('frequency_days', models.PositiveSmallIntegerField(default=1, verbose_name='Периодичность')),
                ('reward', models.CharField(max_length=200, verbose_name='Награда')),
                ('duration_seconds', models.PositiveSmallIntegerField(verbose_name='Продолжительность')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Приятность')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичность')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.habit')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
