# Generated by Django 5.2.5 on 2025-08-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_reminded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
