# Generated by Django 5.2.5 on 2025-09-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0005_alter_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration_seconds',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Награда'),
        ),
    ]
